# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"

pod "XYQuick"

pod 'SDWebImage', '~>3.7'

pod 'MBProgressHUD', '~> 0.9.1'